from pathlib import Path
import lxml



def hparse(html):
    return lxml.html.fromstring(html)


BASE_DOMAIN = 'https://efdsearch.senate.gov'

DATA_PATH = Path('data')


DEFAULT_USER_AGENT = 'Mozilla/5.0 AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36'


DEFAULT_SEARCHDATA_HEADERS =  {
    'Accept': 'application/json, text/javascript, */*; q=0.01',
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'DNT': '1',
    'Origin': 'https://efdsearch.senate.gov',
    'Referer': 'https://efdsearch.senate.gov/search/',
    'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/74.0.3729.169 Safari/537.36',
    'X-CSRFToken': '',
    'X-Requested-With': 'XMLHttpRequest',
}


DEFAULT_SEARCH_PARAMS = {
     'candidate_state': '',
     'senator_state': '',
     'filer_type': ['1', '4', '5'],
     'submitted_start_date': '', # '01/01/2018',
     'submitted_end_date':  '', # '12/31/2018',
     'csrfmiddlewaretoken': 'INSERT_TOKEN',
     'first_name': '',
     'last_name': '',
    }

# DEFAULT_SEARCHDATA_PARAMS = {
#     'draw': ['1'],
#  'columns[0][data]': ['0'],
#  'columns[0][name]': [''],
#  'columns[0][searchable]': ['true'],
#  'columns[0][orderable]': ['true'],
#  'columns[0][search][value]': [''],
#  'columns[0][search][regex]': ['false'],
#  'columns[1][data]': ['1'],
#  'columns[1][name]': [''],
#  'columns[1][searchable]': ['true'],
#  'columns[1][orderable]': ['true'],
#  'columns[1][search][value]': [''],
#  'columns[1][search][regex]': ['false'],
#  'columns[2][data]': ['2'],
#  'columns[2][name]': [''],
#  'columns[2][searchable]': ['true'],
#  'columns[2][orderable]': ['true'],
#  'columns[2][search][value]': [''],
#  'columns[2][search][regex]': ['false'],
#  'columns[3][data]': ['3'],
#  'columns[3][name]': [''],
#  'columns[3][searchable]': ['true'],
#  'columns[3][orderable]': ['true'],
#  'columns[3][search][value]': [''],
#  'columns[3][search][regex]': ['false'],
#  'columns[4][data]': ['4'],
#  'columns[4][name]': [''],
#  'columns[4][searchable]': ['true'],
#  'columns[4][orderable]': ['true'],
#  'columns[4][search][value]': [''],
#  'columns[4][search][regex]': ['false'],
#  'order[0][column]': ['1'],
#  'order[0][dir]': ['asc'],
#  'order[1][column]': ['0'],
#  'order[1][dir]': ['asc'],
#  'start': ['0'],
#  'length': ['100'],
#  'search[value]': [''],
#  'search[regex]': ['false'],
#  'report_types': ['[]'],
#  'filer_types': ['[]'],
#  'submitted_start_date': ['01/01/2012 00:00:00'],
#  'submitted_end_date': [''],
#  'candidate_state': ['IA'],
#  'senator_state': ['IA'],
#  'office_id': [''],
#  'first_name': [''],
#  'last_name': ['']
#  }

DEFAULT_SEARCHDATA_PARAMS = {
 'draw': ['1'],
 'columns[0][data]': ['0'],
 'columns[0][searchable]': ['true'],
 'columns[0][orderable]': ['true'],
 'columns[0][search][regex]': ['false'],
 'columns[1][data]': ['1'],
 'columns[1][searchable]': ['true'],
 'columns[1][orderable]': ['true'],
 'columns[1][search][regex]': ['false'],
 'columns[2][data]': ['2'],
 'columns[2][searchable]': ['true'],
 'columns[2][orderable]': ['true'],
 'columns[2][search][regex]': ['false'],
 'columns[3][data]': ['3'],
 'columns[3][searchable]': ['true'],
 'columns[3][orderable]': ['true'],
 'columns[3][search][regex]': ['false'],
 'columns[4][data]': ['4'],
 'columns[4][searchable]': ['true'],
 'columns[4][orderable]': ['true'],
 'columns[4][search][regex]': ['false'],
 'order[0][column]': ['4'],
 'order[0][dir]': ['desc'],
 'start': ['0'],
 'length': ['100'],
 'search[regex]': ['false'],
 'report_types': ['[]'],
 'filer_types': ['[]'],
 'submitted_start_date': ['01/01/2012 00:00:00'],
 'senator_state': '',
 'candidate_state': '',
}


US_STATES = [
"AK",
"AL",
"AR",
"AZ",
"CA",
"CO",
"CT",
"DE",
"FL",
"GA",
"HI",
"IA",
"ID",
"IL",
"IN",
"KS",
"KY",
"LA",
"MA",
"MD",
"ME",
"MI",
"MN",
"MO",
"MS",
"MT",
"NC",
"ND",
"NE",
"NH",
"NJ",
"NM",
"NV",
"NY",
"OH",
"OK",
"OR",
"PA",
"RI",
"SC",
"SD",
"TN",
"TX",
"UT",
"VA",
"VT",
"WA",
"WI",
"WV",
"WY",
]
